# Generated by Django 5.1 on 2024-10-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('incomplete', 'InComplete')], default='in progress', max_length=11),
        ),
        migrations.AlterField(
            model_name='programenrollment',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('incomplete', 'Incomplete')], default='in porgress', max_length=11),
        ),
    ]
