# Generated by Django 5.1 on 2024-10-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_courseenrollment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programenrollment',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('completed', 'Completed'), ('incomplete', 'Incomplete')], default='in progress', max_length=11),
        ),
    ]
