# Generated by Django 5.1 on 2024-10-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_category_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='decription',
            field=models.TextField(blank=True, default='defaule description.'),
        ),
    ]
