# Generated by Django 5.1 on 2024-08-18 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_programenrollment_program_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_modules', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('number_of_modules_completed', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('date_of_enrollment', models.DateField()),
                ('state', models.CharField(choices=[('accpeted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=8)),
                ('progress', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(default=None, through='user.CourseEnrollment', to='content.course'),
        ),
        migrations.CreateModel(
            name='ProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_courses', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('number_of_courses_completed', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('date_of_enrollment', models.DateField()),
                ('state', models.CharField(choices=[('accpeted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=8)),
                ('progress', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='programs',
            field=models.ManyToManyField(default=None, through='user.ProgramEnrollment', to='content.program'),
        ),
    ]
