# Generated by Django 5.1 on 2024-08-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('m', 'content_manager'), ('c', 'content_consumer')], default='c', max_length=10),
        ),
    ]
