# Generated by Django 5.1 on 2024-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creater',
            field=models.BooleanField(default=False),
        ),
    ]
