# Generated by Django 5.1 on 2024-08-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_creater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
