# Generated by Django 5.1 on 2024-08-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_user_courseenrollment_learner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programenrollment',
            old_name='user',
            new_name='learner',
        ),
    ]
