# Generated by Django 5.1 on 2024-10-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='default test naem', max_length=30, unique=True),
        ),
    ]
