# Generated by Django 5.1 on 2024-10-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='num_tests',
            new_name='num_quizs',
        ),
    ]
