# Generated by Django 5.1 on 2024-10-10 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('course', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='course',
        ),
        migrations.RemoveField(
            model_name='application',
            name='program',
        ),
        migrations.AddField(
            model_name='application',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='program.program'),
        ),
    ]
