# Generated by Django 5.1 on 2024-08-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programenrollment',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programenrollment',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
        migrations.DeleteModel(
            name='ProgramEnrollment',
        ),
    ]
