# Generated by Django 5.1 on 2024-08-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_application_owner_media_owner_module_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateField(default=None),
        ),
    ]
