# Generated by Django 5.1 on 2024-08-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_course_created_at_alter_module_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateField(),
        ),
    ]
