# Generated by Django 5.1 on 2024-08-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_application_user_application_learner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('accpeted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default=None, max_length=20),
        ),
    ]
