# Generated by Django 5.1 on 2024-08-27 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_application_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='course',
        ),
        migrations.RemoveField(
            model_name='application',
            name='program',
        ),
        migrations.AddField(
            model_name='application',
            name='course',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.course'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.program'),
        ),
    ]
