# Generated by Django 5.1 on 2024-08-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_application_course_remove_application_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='course',
        ),
        migrations.RemoveField(
            model_name='application',
            name='program',
        ),
        migrations.AddField(
            model_name='application',
            name='course',
            field=models.ManyToManyField(default=None, to='content.course'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ManyToManyField(default=None, to='content.program'),
        ),
    ]
