# Generated by Django 5.1 on 2024-08-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_application_course_remove_application_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default=None, max_length=20),
        ),
    ]
