# Generated by Django 5.1 on 2024-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_application_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='completed_at',
            field=models.DateField(default=None),
        ),
    ]
