# Generated by Django 5.1 on 2024-08-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_module_completed_remove_module_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='complete_within',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=2),
        ),
        migrations.AddField(
            model_name='program',
            name='complete_within',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=2),
        ),
    ]
