# Generated by Django 5.1 on 2024-09-01 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_course_complete_within_program_complete_within'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnercompletion',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.course'),
        ),
        migrations.AlterField(
            model_name='learnercompletion',
            name='module',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.module'),
        ),
        migrations.AlterField(
            model_name='learnercompletion',
            name='program',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.program'),
        ),
    ]
