# Generated by Django 5.1 on 2024-10-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_module_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_number', models.DecimalField(decimal_places=0, default=None, max_digits=1)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time_limit', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=3)),
                ('pass_score', models.DecimalField(blank=True, decimal_places=0, default=50, max_digits=3)),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_media', to='content.module'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi', models.BooleanField()),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='content.answer')),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='test_question', to='content.test')),
            ],
        ),
    ]
