# Generated by Django 5.1 on 2024-10-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_answer_created_at_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.TextField(default=None),
        ),
    ]
