# Generated by Django 5.1 on 2024-10-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_question_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='num_of_questions',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
