# Generated by Django 5.1 on 2024-10-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_alter_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='module_grade', to='content.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='num_tests',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
