# Generated by Django 5.1 on 2024-10-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_grade_module_module_num_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnercompletion',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
