# Generated by Django 5.1 on 2024-10-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_learnercompletion_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnercompletion',
            name='score',
            field=models.FloatField(),
        ),
    ]
