# Generated by Django 5.1 on 2024-10-05 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_alter_learnercompletion_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='test',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_grade', to='content.test'),
        ),
    ]
