# Generated by Django 5.1 on 2024-10-08 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(default=None)),
                ('multi', models.BooleanField()),
                ('answer', models.TextField()),
                ('created_at', models.DateField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('correct', models.BooleanField()),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_number', models.DecimalField(decimal_places=0, default=None, max_digits=1)),
                ('value', models.TextField()),
                ('created_at', models.DateField(default=None)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='test.question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time_limit', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=3)),
                ('pass_score', models.DecimalField(blank=True, decimal_places=0, default=50, max_digits=3)),
                ('num_of_questions', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('created_at', models.DateField(blank=True, default=None)),
                ('module', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='module.module')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='test_question', to='test.test'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField(default=None)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_grade', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='module_grade', to='module.module')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_grade', to='test.test')),
            ],
        ),
    ]
